# Nimgram
# Copyright (C) 2020-2021 Daniele Cortesi <https://github.com/dadadani>
# This file is part of Nimgram, under the MIT License
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY
# OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

type InputFile* = ref object of RootObj
    id*: int64    ## File ID (generated by client)
    parts*: int32 ## Blocks of the file
    name*: string ## Name of the file

type InputFileSmall* = ref object of InputFile
    md5*: string ## MD5 checksum of the file

proc parse*(inputFile: InputFile): raw.InputFileBig =
    return raw.InputFileBig(
        id: inputFile.id,
        parts: inputFile.parts,
        name: inputFile.name,
    )

proc parse*(inputFile: InputFileSmall): raw.InputFile =
    return raw.InputFile(
        id: inputFile.id,
        parts: inputFile.parts,
        name: inputFile.name,
        md5_checksum: inputFile.md5
    )
